### ISSUE TITLE
a problem with the rf_if: wen/wdata are delayed by 2 cycles unlike the addr

### ISSUE THREAD

**Issue by uhit332** [uhit332/serv#1]
The rf_if delays wenable/wdata by 2 cycles for W=4, but does not delay the waddr. It almost works because apparently the immdec holds the waddr correct, but nothing holds the i_trap. See the trace from formal verification (attached). The code is
```
   0:	cea11373          	csrrw	x6,0xcea,x2
   4:	7a409303          	lh	x6,1956(x1)
   8:	00434033          	xor	x0,x6,x4
```
It traps in the second instruction, then the reg_ch0 test fails for the third (x6 has wrong upper 8 bits). 

[trace.vcd.txt](https://github.com/uhit332/serv/files/13168358/trace.vcd.txt)

**Comment by olofk** [comment]
I think I have found a more generic solution now that aligns the trap signal to the instruction life cycle. Sett here https://github.com/olofk/serv/tree/trap_fix I haven't run the full formal tests on it, but the testing so far looks good
